services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeverse_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - codeverse_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyAWrqovr6OACI9XMH8oP8jkV_Vj-9_PHbA"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "codeverse-b710e.firebaseapp.com"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "codeverse-b710e"

    container_name: codeverse_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=production
      - API_URL=http://caddy/api
      - NEXT_PUBLIC_API_URL=http://caddy/api
    networks:
      - codeverse_net

  caddy:
    image: caddy:2
    container_name: codeverse_caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend
      - frontend
      - db
    networks:
      - codeverse_net

  db:
    image: mysql:8.0
    container_name: codeverse_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: codeverse
      MYSQL_USER: codeverse
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - codeverse_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeverse_migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: npx prisma migrate deploy && npx prisma db seed
    networks:
      - codeverse_net
    profiles:
      - migrate


networks:
  codeverse_net:
    driver: bridge

volumes:
  db_data:
    driver: local
